name: fondue_swap
description: Fondue Swap
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  get: ^4.6.5
  get_storage:
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7

  flutter_secure_storage: ^8.0.0
  crypt: ^4.3.0

  local_auth: ^2.1.6

  thor_devkit_dart: ^1.0.1

  thor_request_dart: ^1.0.2
  web3dart: ^2.7.2
  syncfusion_flutter_sliders: ^24.2.6
  syncfusion_flutter_charts: ^24.2.6
  syncfusion_flutter_core: ^24.2.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/abi/